version: '3.8'
services:
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin:latest
    user: root
    container_name: bitcoin
    command:
      - -datadir=/config
    ports:
      - 18443:18443
      - 18444:18444
      - 18333:18333
      # ZMQ
      - 28332:28332
      - 28333:28333
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-conf=/config/bitcoin.conf", "getblockchaininfo"]
      interval: 2s
      timeout: 1s
      retries: 30
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  # Block explorer server
  electrs:
    image: ghcr.io/vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30000
      - --electrum-rpc-addr
      - 0.0.0.0:50000
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 50000:50000
      - 30000:30000
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  operator:
    container_name: operator
    image: litch/operator
    ports: 
      - 5100:5000
    volumes:
      - ./volumes/operator:/app/server/auth
    depends_on: 
      - lnd

  thunderhub:
    container_name: thunderhub
    image: apotdevin/thunderhub:v0.13.16
    depends_on:
      - bitcoin
      - lnd
    environment:
      ACCOUNT_CONFIG_PATH: '/data/thunderhub.yaml'
    volumes:
      - ./volumes/thunderhub:/data
    ports: 
      - 4200:3000 
  
  # faucet:
  #   container_name: faucet
  #   image: litch/faucet
  #   ports: 
  #     - 8082:8082
  #   depends_on:
  #     - bitcoin

  lnd:
    container_name: lnd
    image: lightninglabs/lnd:v0.16.4-beta
    user: root 
    depends_on:
      bitcoin:
          condition: service_healthy
    volumes:
      - ./volumes/lnd:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "30009:10009" # grpc

  lnd2:
    container_name: lnd2
    image: lightninglabs/lnd:v0.16.1-beta
    user: root
    depends_on:
      bitcoin:
          condition: service_healthy
    volumes:
      - ./volumes/lnd2:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "30010:10009" # grpc

  lnd-15-1:
    container_name: lnd-15-1
    image: lightninglabs/lnd:v0.15.1-beta
    user: root
    depends_on:
      bitcoin:
          condition: service_healthy
    volumes:
      - ./volumes/lnd-15-1:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc

  lnd-15-2:
    container_name: lnd-15-2
    image: lightninglabs/lnd:v0.15.2-beta
    user: root
    depends_on:
      bitcoin:
          condition: service_healthy
    volumes:
      - ./volumes/lnd-15-2:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc

  lnd-15-3:
    container_name: lnd-15-3
    image: lightninglabs/lnd:v0.15.3-beta
    user: root
    depends_on:
      bitcoin:
          condition: service_healthy
    volumes:
      - ./volumes/lnd-15-3:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc
    
  lnd-15-5:
    container_name: lnd-15-5
    image: lightninglabs/lnd:v0.15.5-beta
    user: root
    depends_on:
      bitcoin:
          condition: service_healthy
    volumes:
      - ./volumes/lnd-15-5:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "30011:10009" # grpc
  

  lightning-hub:
    container_name: cln-hub
    image: elementsproject/lightningd:v0.12.1
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-hub
      - --large-channels
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-hub:/root/.lightning
  
  lightning-remote:
    container_name: cln-remote
    image: elementsproject/lightningd:v0.12.1
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-remote
      - --large-channels
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-remote:/root/.lightning

  lightning-child1:
    container_name: cln-c1
    image: litch/cln-splicing:latest
    environment:
      EXPOSE_TCP: "true"
      
    command: 
      - --network=regtest 
      - --alias=coreln-c1
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug
      - --experimental-splicing
      - --dev-fast-gossip
      - --bind-addr=0.0.0.0:9735 
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c1:/root/.lightning

  lightning-child2:
    container_name: cln-c2
    image: litch/cln-splicing:latest
    environment:
      EXPOSE_TCP: "true"
      
    command: 
      - --network=regtest 
      - --alias=coreln-c2
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --experimental-splicing
      - --dev-fast-gossip
      - --bind-addr=0.0.0.0:9735
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c2:/root/.lightning

  lightning-child3:
    container_name: cln-c3
    image: litch/cln-splicing:latest
    environment:
      EXPOSE_TCP: "true"
      
    command: 
      - --network=regtest 
      - --alias=coreln-c3
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --experimental-splicing
      - --bind-addr=0.0.0.0:9735
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c3:/root/.lightning

  lightning-child4:
    container_name: cln-c4
    image: elementsproject/lightningd:v0.11.1
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-c4
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      bitcoin:
        condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c4:/root/.lightning

  cln-sluggish:
    container_name: cln-sluggish
    image: litch/cln-sluggish:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=cln-sluggish
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
      - --plugin=/sluggish
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/cln-sluggish:/root/.lightning

  cln-spaz:
    container_name: cln-spaz
    image: litch/cln-spaz:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=cln-spaz
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
      - --plugin=/spaz
    depends_on:
      bitcoin:
          condition: service_healthy
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/cln-spaz:/root/.lightning

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    volumes:
      - ./resources/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./volumes/prometheus:/prometheus
    restart: unless-stopped
  
  node-exporter:
    image: prom/node-exporter:latest
    ports: 
      - 9100:9100
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    ports:
      - 3000:3015
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123
    restart: unless-stopped
    depends_on:
      - prometheus
