version: '3.8'
services:
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin:latest
    user: root
    container_name: bitcoin
    command:
      - -datadir=/config
    ports:
      - 18443:18443
      - 18444:18444
      - 18333:18333
      # ZMQ
      - 28332:28332
      - 28333:28333
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  operator:
    container_name: operator
    image: litch/operator
    ports: 
      - 5100:5000

  thunderhub:
    container_name: thunderhub
    image: apotdevin/thunderhub:v0.13.16
    depends_on:
      - bitcoin
      - lnd
    environment:
      ACCOUNT_CONFIG_PATH: '/data/thunderhub.yaml'
    volumes:
      - ./volumes/thunderhub:/data
    ports: 
      - 4200:3000 
    

  lnd:
    container_name: lnd
    image: lightninglabs/lnd:v0.15.3-beta
    user: root 
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "30009:10009" # grpc

  lnd-15-0:
    container_name: lnd-15-0
    image: lightninglabs/lnd:v0.15.0-beta
    user: root
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd-15-0:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc

  lnd-15-1:
    container_name: lnd-15-1
    image: lightninglabs/lnd:v0.15.1-beta
    user: root
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd-15-1:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc

  lnd-15-2:
    container_name: lnd-15-2
    image: lightninglabs/lnd:v0.15.2-beta
    user: root
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd-15-2:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc

  lnd-15-3:
    container_name: lnd-15-3
    image: lightninglabs/lnd:v0.15.3-beta
    user: root
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd-15-3:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "10009" # grpc


  lnd2:
    container_name: lnd2
    image: lightninglabs/lnd:v0.15.1-beta
    user: root
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd2:/root/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735" # p2p
      - "30010:10009" # grpc


  lightning-hub:
    container_name: cln-hub
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-hub
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-hub:/root/.lightning
  
  lightning-remote:
    container_name: cln-remote
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-remote
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-remote:/root/.lightning

  lightning-child1:
    container_name: cln-c1
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-c1
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug
      - --bind-addr=0.0.0.0:9735 
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c1:/root/.lightning

  lightning-child2:
    container_name: cln-c2
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-c2
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c2:/root/.lightning

  lightning-child3:
    container_name: cln-c3
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-c3
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c3:/root/.lightning

  lightning-child4:
    container_name: cln-c4
    image: elementsproject/lightningd:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=coreln-c4
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c4:/root/.lightning
