version: '3.8'
services:
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin:latest
    user: 1000:1000
    container_name: bitcoin
    command:
      - -datadir=config
    ports:
      - 18443:18443
      - 18444:18444
      # ZMQ
      - 28332:28332
      - 28333:28333
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  lightning-hub:
    container_name: cln-hub
    image: docker.io/litch/clightning:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=cln-hub
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-hub:/root/.lightning
    platform: "linux/amd64"
  
  lightning-remote:
    container_name: cln-remote
    image: docker.io/litch/clightning:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=cln-remote
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-remote:/root/.lightning
    platform: "linux/amd64"

  lightning-child1:
    container_name: cln-c1
    image: docker.io/litch/clightning:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=nigiri
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug
      - --bind-addr=0.0.0.0:9735 
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c1:/root/.lightning

  lightning-child2:
    container_name: cln-c2
    image: docker.io/litch/clightning:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=nigiri
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c2:/root/.lightning

  lightning-child3:
    container_name: cln-c3
    image: docker.io/litch/clightning:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=nigiri
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c3:/root/.lightning

  lightning-child4:
    container_name: cln-c4
    image: docker.io/litch/clightning:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=nigiri
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd-c4:/root/.lightning
