networks:
  default:
    name: lightning-conformance
    external: true

services:
  cln-spaz:
    container_name: cln-spaz
    image: litch/cln-spaz:latest
    environment:
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=cln-spaz
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --bind-addr=0.0.0.0:9735
      - --plugin=/spaz
    depends_on:
      - bitcoin
    ports:
      - 9735 # p2p
      - 9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/cln-spaz:/root/.lightning
