FROM elementsproject/lightningd:latest as blockstream

ADD https://github.com/litch/sluggish/releases/latest/download/download/sluggish-x86_64-unknown-linux-musl.tar.gz /

RUN tar xvf sluggish-x86_64-unknown-linux-musl.tar.gz
RUN rm sluggish-x86_64-unknown-linux-musl.tar.gz
