FROM elementsproject/lightningd:latest as blockstream

ADD https://github.com/litch/spaz/releases/latest/download/spaz-x86_64-unknown-linux-musl.tar.gz /

RUN tar xvf spaz-x86_64-unknown-linux-musl.tar.gz
RUN rm spaz-x86_64-unknown-linux-musl.tar.gz
